changeLanguage = 'Выбран Русский язык!'
chooseLanguage = 'Выберите язык.'
mainMenu = 'Главное меню!'
infoMessage = 'Данный бот предназначен для...'
waitMessage = 'Подождите, пожалуйста...'
menuAction = 'Выберите команду с клавиатуры.'
pictFinderStart = 'Поиск картинок по запросу. Введите в чат любой запрос и бот найдет для Вас картинку.'
status = 'Ваш уровень: '
YouTubeDownloaderWelcome = 'Активирован загрузчик видео с YouTube.\nВышлите ссылку на видео в чат.'

